TUPLE_A1 = ('Ozira', 'Althen', 'Valica')
TUPLE_A2 = ('Hollant', 'Samitra', 'Limen')
TUPLE_A3 = ('Viserna', 'Colvand', 'Galamar')
TUPLE_A4 = ('Beregand', 'Iverna', 'Alconde')
TUPLE_A5 = ('Landsey', 'Uldan', 'Askera')
TUPLE_A6 = ('Cantel', 'Lomell', 'Aquita')